name: Lighthouse PWA Audit

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install lighthouse
        run: npm install -g lighthouse@10

      - name: Setup Chrome for CI
        id: setup_chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: 'latest'

      - name: Run Lighthouse (PWA)
        id: run_lighthouse
        env:
          TARGET_URL: ${{ secrets.LIGHTHOUSE_URL || 'https://loto-app-45ud.onrender.com' }}
          CHROME_PATH: ${{ steps.setup_chrome.outputs.chrome_path }}
        run: |
          mkdir -p reports
          # JSON and HTML outputs. Use the chrome path installed by the setup action and pass headless flags.
          lighthouse "$TARGET_URL" --only-categories=pwa --output=json --output=html --output-path=reports/lighthouse --chrome-path="$CHROME_PATH" --chrome-flags="--headless --no-sandbox --disable-gpu --disable-dev-shm-usage"
          ls -la reports

      - name: Upload Lighthouse reports
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: reports
